sonar.projectKey=user-management
sonar.projectName=User Management
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/test-results/**,**/__pycache__/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.qualitygate.wait=true